name: AWS module CI

on:
  pull_request:
    paths:
      - "aws/**"
      - "terraform-aws-*/**"
      - "mirrors.conf"
      - ".github/workflows/aws-module-ci.yml"

jobs:
  lint:
    uses: ./.github/workflows/terraform-lint.yml
    with:
      working_directory: aws/sre-tf-eks
      run_tflint: true

  validate:
    uses: ./.github/workflows/terraform-validate.yml
    with:
      working_directory: aws/sre-tf-eks
      run_tests: false
