name: "Debug region caller"

on:
  workflow_dispatch: {}

jobs:
  plan:
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        region: [eastus, westus2]
    uses: manubalasree-homelab/sre-tf-homelab/.github/workflows/per-region-plan.yml@main
    with:
      working_directory: demos/scaling-demo
      plan_artifact_name: tfplan-region-${{ matrix.region }}
      tfvars_json: '{"region":"${{ matrix.region }}"}'

  apply:
    needs: plan
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        region: [eastus, westus2]
    uses: manubalasree-homelab/sre-tf-homelab/.github/workflows/per-region-apply.yml@main
    with:
      working_directory: demos/scaling-demo
      plan_artifact_name: tfplan-region-${{ matrix.region }}
